insert into permissions("name","description","code") values('主界面','主界面访问权限',1);
insert into permissions("name","description","code") values('购货单','购货单访问权限',2);
insert into permissions("name","description","code") values('购货退货单','购货退货单访问权限',3);
insert into permissions("name","description","code") values('销售单','销售单访问权限',4);
insert into permissions("name","description","code") values('销售退货单','销售退货单访问权限',5);
insert into permissions("name","description","code") values('供应商管理','供应商管理访问权限',6);
insert into permissions("name","description","code") values('库存管理','库存管理访问权限',7);
insert into permissions("name","description","code") values('配件管理','配件管理访问权限',8);
insert into permissions("name","description","code") values('系统维护','系统维护访问权限',9);